# pokeapi の pokemon ID とのマッピング

mapping:
  - "892-0": 892 #ウーラオス(いちげきのかた)
  - "892-1": 10191 #ウーラオス(れんげきのかた)
  - "641-0": 641 #トルネロス(けしんフォルム)
  - "641-1": 10019 #トルネロス(れいじゅうフォルム)
  - "642-0": 642 #ボルトロス(けしんフォルム)
  - "642-1": 10020 #ボルトロス(れいじゅうフォルム)
  - "645-0": 645 #ランドロス(けしんフォルム)
  - "645-1": 10021 #ランドロス(れいじゅうフォルム)
  - "905-0": 905 #ラブトロス(けしんフォルム)
  - "905-1": 10249 #ラブトロス(れいじゅうフォルム)
  - "1017-0": 1017 #オーガポン(みどりのめん)
  - "1017-1": 10273 #オーガポン(いどのめん)
  - "1017-2": 10274 #オーガポン(かまどのめん)
  - "1017-3": 10275 #オーガポン(いしずえのめん)
  - "678-0": 678 #ニャオニクス(オスのすがた)
  - "678-1": 10025 #ニャオニクス(メスのすがた)
  #- "901-0": #ガチグマ
  - "901-1": 10272 #ガチグマ(アカツキ)
  - "902-0": 902 #イダイトウ(オスのすがた)
  - "902-1": 10248 #イダイトウ(メスのすがた)
  #- "479-0": #ロトム(ロトムのすがた)
  - "479-1": 10008 #ロトム(ヒートロトム)
  - "479-2": 10009 #ロトム(ウォッシュロトム)
  - "479-3": 10010 #ロトム(フロストロトム)
  - "479-4": 10011 #ロトム(スピンロトム)
  - "479-5": 10012 #ロトム(カットロトム)
  - "876-0": 876 #イエッサン(オスのすがた)
  - "876-1": 10186 #イエッサン(メスのすがた)
  - "741-0": 741 #オドリドリ(めらめらスタイル)
  - "741-1": 10123 #オドリドリ(ぱちぱちスタイル)
  - "741-2": 10124 #オドリドリ(ふらふらスタイル)
  - "741-3": 10125 #オドリドリ(まいまいスタイル)
  - "745-0": 745 #"ルガルガン(まひるのすがた)",
  - "745-1": 10126 #ルガルガン(まよなかのすがた)
  - "745-2": 10152 #ルガルガン(たそがれのすがた)
  - "26-1": 10100 #ライチュウ(アローラのすがた)
  - "51-1": 10106 #ダグトリオ(アローラのすがた)
  - "53-1": 10108 #ペルシアン(アローラのすがた)
  - "89-1": 10113 #ベトベトン(アローラのすがた)
  - "76-1": 10111 #ゴローニャ(アローラのすがた)
  - "38-1": 10104 #キュウコン(アローラのすがた)
  - "28-1": 10102 #サンドパン(アローラのすがた)
  - "103-1": 10114 #ナッシー(アローラのすがた)
  - "110-1": 10167 #マタドガス(ガラルのすがた)
  - "80-2": 10165 #ヤドラン(ガラルのすがた)
  - "199-1": 10172 #ヤドキング(ガラルのすがた)
  - "144-1": 10169 #フリーザー(ガラルのすがた)
  - "145-1": 10170 #サンダー(ガラルのすがた)
  - "146-1": 10171 #ファイヤー(ガラルのすがた)
  - "724-1": 10244 #ジュナイパー(ヒスイのすがた)
  - "157-1": 10233 #バクフーン(ヒスイのすがた)
  - "503-1": 10236 #ダイケンキ(ヒスイのすがた)
  - "571-1": 10239 #ゾロアーク(ヒスイのすがた)
  - "59-1": 10230 #ウインディ(ヒスイのすがた)
  - "101-1": 10232 #マルマイン(ヒスイのすがた)
  - "706-1": 10242 #ヌメルゴン(ヒスイのすがた)
  - "549-1": 10237 #ドレディア(ヒスイのすがた)
  - "628-1": 10240 #ウォーグル(ヒスイのすがた)
  - "713-1": 10243 #クレベース(ヒスイのすがた)
  - "128-1": 10250 #ケンタロス(パルデアのすがた・コンバット種)
  - "128-2": 10251 #ケンタロス(パルデアのすがた・ブレイズ種)
  - "128-3": 10252 #ケンタロス(パルデアのすがた・ウォーター種)
