# 内部ID(Homeベース) と 名前の組
pokemons:
  - 3-0: フシギバナ
  - 6-0: リザードン
  - 9-0: カメックス
  - 24-0: アーボック
  - 26-0: ライチュウ
  - 26-1: ライチュウ(アローラのすがた)
  - 28-0: サンドパン
  - 28-1: サンドパン(アローラのすがた)
  - 36-0: ピクシー
  - 38-0: キュウコン
  - 38-1: キュウコン(アローラのすがた)
  - 40-0: プクリン
  - 45-0: ラフレシア
  - 49-0: モルフォン
  - 51-0: ダグトリオ
  - 51-1: ダグトリオ(アローラのすがた)
  - 53-0: ペルシアン
  - 53-1: ペルシアン(アローラのすがた)
  - 55-0: ゴルダック
  - 59-0: ウインディ
  - 59-1: ウインディ(ヒスイのすがた)
  - 62-0: ニョロボン
  - 71-0: ウツボット
  - 73-0: ドククラゲ
  - 76-0: ゴローニャ
  - 76-1: ゴローニャ(アローラのすがた)
  - 80-0: ヤドラン
  - 80-2: ヤドラン(ガラルのすがた)
  - 82-0: レアコイル
  - 85-0: ドードリオ
  - 87-0: ジュゴン
  - 89-0: ベトベトン
  - 89-1: ベトベトン(アローラのすがた)
  - 91-0: パルシェン
  - 94-0: ゲンガー
  - 97-0: スリーパー
  - 101-0: マルマイン
  - 101-1: マルマイン(ヒスイのすがた)
  - 103-0: ナッシー
  - 103-1: ナッシー(アローラのすがた)
  - 106-0: サワムラー
  - 107-0: エビワラー
  - 110-0: マタドガス
  - 110-1: マタドガス(ガラルのすがた)
  - 112-0: サイドン
  - 113-0: ラッキー
  - 123-0: ストライク
  - 128-0: ケンタロス
  - 128-1: ケンタロス(パルデアのすがた・コンバット種)
  - 128-2: ケンタロス(パルデアのすがた・ブレイズ種)
  - 128-3: ケンタロス(パルデアのすがた・ウォーター種)
  - 130-0: ギャラドス
  - 131-0: ラプラス
  - 132-0: メタモン
  - 134-0: シャワーズ
  - 135-0: サンダース
  - 136-0: ブースター
  - 143-0: カビゴン
  - 144-0: フリーザー
  - 144-1: フリーザー(ガラルのすがた)
  - 145-0: サンダー
  - 145-1: サンダー(ガラルのすがた)
  - 146-0: ファイヤー
  - 146-1: ファイヤー(ガラルのすがた)
  - 149-0: カイリュー
  - 154-0: メガニウム
  - 157-0: バクフーン
  - 157-1: バクフーン(ヒスイのすがた)
  - 160-0: オーダイル
  - 162-0: オオタチ
  - 164-0: ヨルノズク
  - 168-0: アリアドス
  - 171-0: ランターン
  - 181-0: デンリュウ
  - 182-0: キレイハナ
  - 184-0: マリルリ
  - 185-0: ウソッキー
  - 186-0: ニョロトノ
  - 189-0: ワタッコ
  - 192-0: キレイハナ
  - 195-0: ヌオー
  - 196-0: エーフィ
  - 197-0: ブラッキー
  - 199-0: ヤドキング
  - 199-1: ヤドキング(ガラルのすがた)
  - 205-0: フォレトス
  - 210-0: グランブル
  - 212-0: ハッサム
  - 214-0: ヘラクロス
  - 219-0: マグカルゴ
  - 227-0: エアームド
  - 229-0: ヘルガー
  - 230-0: キングドラ
  - 232-0: ドンファン
  - 233-0: ポリゴン2
  - 237-0: カポエラー
  - 242-0: ハピナス
  - 243-0: ライコウ
  - 244-0: エンテイ
  - 245-0: スイクン
  - 248-0: バンギラス
  - 254-0: ジュカイン
  - 257-0: バシャーモ
  - 260-0: ラグラージ
  - 272-0: ルンパッパ
  - 275-0: ダーテング
  - 279-0: ペリッパー
  - 282-0: サーナイト
  - 286-0: キノガッサ
  - 289-0: ケッキング
  - 297-0: ハリテヤマ
  - 302-0: ヤミラミ
  - 308-0: チャーレム
  - 317-0: マルノーム
  - 323-0: バクーダ
  - 324-0: コータス
  - 326-0: ブーピッグ
  - 330-0: フライゴン
  - 332-0: ノクタス
  - 334-0: チルタリス
  - 340-0: ナマズン
  - 342-0: シザリガー
  - 350-0: ミロカロス
  - 354-0: ジュペッタ
  - 356-0: サマヨール
  - 357-0: トロピウス
  - 358-0: チリーン
  - 362-0: オニゴーリ
  - 373-0: ボーマンダ
  - 376-0: メタグロス
  - 377-0: レジロック
  - 378-0: レジアイス
  - 379-0: レジスチル
  - 380-0: ラティアス
  - 381-0: ラティオス
  - 389-0: ドダイトス
  - 392-0: ゴウカザル
  - 395-0: エンペルト
  - 397-0: ムクホーク
  - 402-0: コロトック
  - 405-0: レントラー
  - 409-0: ラムパルド
  - 411-0: トリデプス
  - 416-0: ビークイン
  - 417-0: パチリス
  - 419-0: フローゼル
  - 423-0: トリトドン
  - 424-0: エテボース
  - 426-0: フワライド
  - 429-0: ムウマージ
  - 430-0: ドンカラス
  - 435-0: スカタンク
  - 437-0: ドータクン
  - 442-0: ミカルゲ
  - 445-0: ガブリアス
  - 448-0: ルカリオ
  - 450-0: カバルドン
  - 454-0: ドクロッグ
  - 457-0: ネオラント
  - 460-0: ユキノオー
  - 461-0: マニューラ
  - 462-0: ジバコイル
  - 464-0: ドサイドン
  - 466-0: エレキブル
  - 467-0: ブーバーン
  - 469-0: メガヤンマ
  - 470-0: リーフィア
  - 471-0: グレイシア
  - 472-0: グライオン
  - 473-0: マンムー
  - 474-0: ポリゴンZ
  - 475-0: エルレイド
  - 476-0: ダイノーズ
  - 477-0: ヨノワール[
  - 478-0: ユキメノコ
  - 479-0: ロトム
  - 479-1: ロトム(ヒートロトム)
  - 479-2: ロトム(ウォッシュロトム)
  - 479-3: ロトム(フロストロトム)
  - 479-4: ロトム(スピンロトム)
  - 479-5: ロトム(カットロトム)
  - 480-0: ユクシー
  - 481-0: エムリット
  - 482-0: アグノム
  - 485-0: ヒードラン
  - 486-0: レジギガス
  - 488-0: クレセリア
  - 497-0: ジャローダ
  - 500-0: エンブオー
  - 503-0: ダイケンキ
  - 503-1: ダイケンキ(ヒスイのすがた)
  - 523-0: ゼブライカ
  - 530-0: ドリュウズ
  - 534-0: ローブシン
  - 542-0: ハハコモリ
  - 547-0: エルフーン
  - 549-0: ドレディア
  - 549-1: ドレディア(ヒスイのすがた)
  - 553-0: ワルビアル
  - 560-0: ズルズキン
  - 571-0: ゾロアーク
  - 571-1: ゾロアーク(ヒスイのすがた)
  - 573-0: チラチーノ
  - 576-0: ゴチルゼル
  - 579-0: ランクルス
  - 581-0: スワンナ
  - 586-0: メブキジカ
  - 591-0: モロバレル
  - 594-0: ママンボウ
  - 596-0: デンチュラ
  - 604-0: シビルドン
  - 609-0: シャンデラ
  - 612-0: オノノクス
  - 614-0: ツンベアー
  - 615-0: フリージオ
  - 620-0: コジョンド
  - 623-0: ゴルーグ
  - 625-0: キリキザン
  - 628-0: ウォーグル
  - 628-1: ウォーグル(ヒスイのすがた)
  - 630-0: バルジーナ
  - 635-0: サザンドラ
  - 637-0: ウルガモス
  - 638-0: コバルオン
  - 639-0: テラキオン
  - 640-0: ビリジオン
  - 641-0: トルネロス(けしんフォルム)
  - 641-1: トルネロス(れいじゅうフォルム)
  - 642-0: ボルトロス(けしんフォルム)
  - 642-1: ボルトロス(れいじゅうフォルム)
  - 645-0: ランドロス(けしんフォルム)
  - 645-1: ランドロス(れいじゅうフォルム)
  - 652-0: ブリガロン
  - 655-0: マフォクシー
  - 658-0: ゲッコウガ
  - 663-0: ファイアロー
  - 666-0: ビビヨン
  - 668-0: カエンジシ
  - 671-0: フラージェス
  - 673-0: ゴーゴート
  - 678-0: ニャオニクス(オスのすがた)
  - 678-1: ニャオニクス(メスのすがた)
  - 687-0: カラマネロ
  - 691-0: ドラミドロ
  - 693-0: ブロスター
  - 700-0: ニンフィア
  - 701-0: ルチャブル
  - 702-0: デデンネ
  - 703-0: メレシー
  - 706-0: ヌメルゴン
  - 706-1: ヌメルゴン(ヒスイのすがた)
  - 707-0: クレッフィ
  - 709-0: オーロット
  - 713-0: クレベース
  - 713-1: クレベース(ヒスイのすがた)
  - 715-0: オンバーン
  - 724-0: ジュナイパー
  - 724-1: ジュナイパー(ヒスイのすがた)
  - 727-0: ガオガエン
  - 730-0: アシレーヌ
  - 733-0: ドデカバシ
  - 735-0: デカグース
  - 738-0: クワガノン
  - 740-0: ケケンカニ
  - 741-0: オドリドリ(めらめらスタイル)
  - 741-1: オドリドリ(ぱちぱちスタイル)
  - 741-2: オドリドリ(ふらふらスタイル)
  - 741-3: オドリドリ(まいまいスタイル)
  - 743-0: アブリボン
  - 745-0: ルガルガン(まひるのすがた)
  - 745-1: ルガルガン(まよなかのすがた)
  - 745-2: ルガルガン(たそがれのすがた)
  - 748-0: ドヒドイデ
  - 750-0: バンバドロ
  - 752-0: オニシズクモ
  - 754-0: ラランテス
  - 758-0: エンニュート
  - 763-0: アマージョ
  - 764-0: キュワワー
  - 765-0: ヤレユータン
  - 766-0: ナゲツケサル
  - 770-0: シロデスナ
  - 774-0: メテノ
  - 775-0: ネッコアラ
  - 778-0: ミミッキュ
  - 779-0: ハギギシリ
  - 784-0: ジャラランガ
  - 812-0: ゴリランダー
  - 815-0: エースバーン
  - 818-0: インテレオン
  - 820-0: ヨクバリス
  - 823-0: アーマーガア
  - 834-0: カジリガメ
  - 839-0: セキタンザン
  - 841-0: アップリュー
  - 842-0: タルップル
  - 844-0: サダイジャ
  - 845-0: ウッウ
  - 847-0: カマスジョー
  - 849-0: ストリンダー
  - 855-0: ポットデス
  - 858-0: ブリムオン
  - 861-0: オーロンゲ
  - 863-0: ニャイキング
  - 869-0: マホイップ
  - 870-0: タイレーツ
  - 871-0: バチンウニ
  - 873-0: モスノウ
  - 874-0: イシヘンジン
  - 875-0: コオリッポ
  - 876-0: イエッサン(オスのすがた)
  - 876-1: イエッサン(メスのすがた)
  - 877-0: モルペコ
  - 879-0: ダイオウドウ
  - 884-0: ジュラルドン
  - 887-0: ドラパルト
  - 892-0: ウーラオス(いちげきのかた)
  - 892-1: ウーラオス(れんげきのかた)
  - 894-0: レジエレキ
  - 895-0: レジドラゴ
  - 896-0: ブリザポス
  - 897-0: レイスポス
  - 899-0: アヤシシ
  - 900-0: バサギリ
  - 901-0: ガチグマ
  - 901-1: ガチグマ(アカツキ)
  - 902-0: イダイトウ(オスのすがた)
  - 902-1: イダイトウ(メスのすがた)
  - 903-0: オオニューラ
  - 904-0: ハリーマン
  - 905-0: ラブトロス(けしんフォルム)
  - 905-1: ラブトロス(れいじゅうフォルム)
  - 908-0: マスカーニャ
  - 911-0: ラウドボーン
  - 914-0: ウェーニバル
  - 916-0: パフュートン
  - 918-0: ワナイダー
  - 920-0: エクスレッグ
  - 923-0: パーモット
  - 925-0: イッカネズミ
  - 927-0: バウッツェル
  - 930-0: オリーヴァ
  - 931-0: イキリンコ
  - 934-0: キョジオーン
  - 936-0: グレンアルマ
  - 937-0: ソウブレイズ
  - 939-0: ハラバリー
  - 941-0: タイカイデン
  - 943-0: マフィティフ
  - 945-0: タギングル
  - 947-0: アノホラグサ
  - 949-0: リククラゲ
  - 950-0: ガケガニ
  - 952-0: スコヴィラン
  - 954-0: ベラカス
  - 956-0: クエスパトラ
  - 959-0: デカヌチャン
  - 961-0: ウミトリオ
  - 964-0: イルカマン(ナイーブフォルム)
  - 964-1: イルカマン(マイティフォルム)
  - 966-0: ブロロローム
  - 967-0: モトトカゲ
  - 968-0: ミミズズ
  - 970-0: キラフロル
  - 972-0: ハカドッグ
  - 973-0: カラミンゴ
  - 975-0: ハルクジラ
  - 976-0: ミガルーサ
  - 977-0: ヘイラッシャ
  - 978-0: シャリタツ
  - 979-0: コノヨザル
  - 980-0: ドオー
  - 981-0: リキキリン
  - 982-0: ノココッチ
  - 983-0: ドドゲザン
  - 984-0: イダイナキバ
  - 985-0: サケブシッポ
  - 986-0: アラブルタケ
  - 987-0: ハバタクカミ
  - 988-0: チヲハウハネ
  - 989-0: スナノケガワ
  - 990-0: テツノワダチ
  - 991-0: テツノツツミ
  - 992-0: テツノカイナ
  - 993-0: テツノコウベ
  - 994-0: テツノドクガ
  - 995-0: テツノイバラ
  - 998-0: セグレイブ
  - 1000-0: サーフゴー
  - 1001-0: チオンジェン
  - 1002-0: パオジアン
  - 1003-0: ディンルー
  - 1004-0: イーユイ
  - 1005-0: トドロクツキ
  - 1006-0: テツノブシン
  - 1009-0: ウネルミナモ
  - 1010-0: テツノイサハ
  - 1011-0: カミッチュ
  - 1013-0: ヤバソチャ
  - 1014-0: イイネイヌ
  - 1015-0: マシマシラ
  - 1016-0: キチキギス
  - 1017-0: オーガポン(みどりのめん)
  - 1017-1: オーガポン(いどのめん)
  - 1017-2: オーガポン(かまどのめん)
  - 1017-3: オーガポン(いしずえのめん)
  - 1018-0: ブリジュラス
  - 1019-0: カミツオロチ
  - 1020-0: ウガツホムラ
  - 1021-0: タケルライコ
  - 1022-0: テツノイワオ
  - 1023-0: テツノカシラ
